/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u08766083141
 */
public class JDlgKsmClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMpvUsuarios
     */
    public JDlgKsmClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
        
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmNome.setEnabled(false);
        jTxtKsmCep.setEnabled(false);
        jFmtKsmCpf.setEnabled(false);
        jTxtKsmApelido.setEnabled(false);
        jFmtKsmRg.setEnabled(false);
        jFmtKsmDataNasc.setEnabled(false);
        jCboKsmNivel.setEnabled(false);
        jTxtKsmNumero.setEnabled(false);
        jTxtKsmEmail.setEnabled(false);
        jTxtKsmBairro.setEnabled(false);
        jTxtKsmCelular.setEnabled(false);
        jTxtKsmLogradouro.setEnabled(false);
        jTxtKsmCidade.setEnabled(false);
        jCboKsmAtivo.setEnabled(false);
        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);
        
     
    }
    public void habilitar(boolean valor){
        jTxtKsmCodigo.setEnabled(valor);
        jTxtKsmNome.setEnabled(valor);
        jTxtKsmCep.setEnabled(valor);
        jFmtKsmCpf.setEnabled(valor);
        jTxtKsmApelido.setEnabled(valor);
        jFmtKsmRg.setEnabled(valor);
        jFmtKsmDataNasc.setEnabled(valor);
        jCboKsmNivel.setEnabled(valor);
        jTxtKsmNumero.setEnabled(valor);
        jTxtKsmEmail.setEnabled(valor);
        jTxtKsmBairro.setEnabled(valor);
        jTxtKsmCelular.setEnabled(valor);
        jTxtKsmLogradouro.setEnabled(valor);
        jTxtKsmCidade.setEnabled(valor);
        jCboKsmAtivo.setEnabled(valor);
        jBtnKsmCancelar.setEnabled(valor);
        jBtnKsmConfirmar.setEnabled(valor);

        jBtnKsmAlterar.setEnabled(! valor);
        jBtnKsmIncluir.setEnabled(! valor);
        jBtnKsmExcluir.setEnabled(! valor);
        jBtnKsmPesquisar.setEnabled(! valor);
    
    }
    public void Desabilitar (){
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmNome.setEnabled(false);
        jTxtKsmCep.setEnabled(false);
        jFmtKsmCpf.setEnabled(false);
        jTxtKsmApelido.setEnabled(false);
        jFmtKsmRg.setEnabled(false);
        jFmtKsmDataNasc.setEnabled(false);
        jCboKsmNivel.setEnabled(false);
        jTxtKsmNumero.setEnabled(false);
      
        jTxtKsmEmail.setEnabled(false);
        jTxtKsmBairro.setEnabled(false);
        jTxtKsmCelular.setEnabled(false);
        jTxtKsmLogradouro.setEnabled(false);
        jTxtKsmCidade.setEnabled(false);
        jCboKsmAtivo.setEnabled(false);
        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);

        jBtnKsmAlterar.setEnabled(true);
        jBtnKsmIncluir.setEnabled(true);
        jBtnKsmExcluir.setEnabled(true);
        jBtnKsmPesquisar.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Código = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtKsmCodigo = new javax.swing.JTextField();
        jTxtKsmNome = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFmtKsmRg = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtKsmDataNasc = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jCboKsmNivel = new javax.swing.JComboBox<>();
        jCboKsmAtivo = new javax.swing.JCheckBox();
        jBtnKsmPesquisar = new javax.swing.JButton();
        jBtnKsmCancelar = new javax.swing.JButton();
        jBtnKsmAlterar = new javax.swing.JButton();
        jBtnKsmIncluir = new javax.swing.JButton();
        jBtnKsmConfirmar = new javax.swing.JButton();
        jBtnKsmExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtKsmEmail = new javax.swing.JTextField();
        jFmtKsmCpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtKsmCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtKsmCep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtKsmApelido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtKsmNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtKsmLogradouro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtKsmBairro = new javax.swing.JTextField();
        jTxtKsmCidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Código.setText("Código");

        jLabel1.setText("Nome");

        jTxtKsmCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCodigoActionPerformed(evt);
            }
        });

        jTxtKsmNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmNomeActionPerformed(evt);
            }
        });

        jLabelCpf.setText("Cpf");

        jLabel3.setText("Rg");

        jFmtKsmRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtKsmRgActionPerformed(evt);
            }
        });

        jLabel4.setText("Data de Nascimento");

        jLabel5.setText("Nivel");

        jCboKsmNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1", "item 2", "item 3", "item 4" }));
        jCboKsmNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboKsmNivelActionPerformed(evt);
            }
        });

        jCboKsmAtivo.setText("Ativo");
        jCboKsmAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboKsmAtivoActionPerformed(evt);
            }
        });

        jBtnKsmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnKsmPesquisar.setText("Pesquisar");
        jBtnKsmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmPesquisarActionPerformed(evt);
            }
        });

        jBtnKsmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnKsmCancelar.setText("Cancelar");
        jBtnKsmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmCancelarActionPerformed(evt);
            }
        });

        jBtnKsmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnKsmAlterar.setText("Alterar");
        jBtnKsmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmAlterarActionPerformed(evt);
            }
        });

        jBtnKsmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnKsmIncluir.setText("Incluir");
        jBtnKsmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmIncluirActionPerformed(evt);
            }
        });

        jBtnKsmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnKsmConfirmar.setText("Confirmar");
        jBtnKsmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmConfirmarActionPerformed(evt);
            }
        });

        jBtnKsmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnKsmExcluir.setText("Excluir");
        jBtnKsmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jTxtKsmEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmEmailActionPerformed(evt);
            }
        });

        jFmtKsmCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtKsmCpfActionPerformed(evt);
            }
        });

        jLabel7.setText("Celular");

        jTxtKsmCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCelularActionPerformed(evt);
            }
        });

        jLabel8.setText("Cep");

        jTxtKsmCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCepActionPerformed(evt);
            }
        });

        jLabel9.setText("Apelido");

        jTxtKsmApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmApelidoActionPerformed(evt);
            }
        });

        jLabel10.setText("Numero");

        jTxtKsmNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmNumeroActionPerformed(evt);
            }
        });

        jLabel11.setText("Bairro");

        jTxtKsmLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmLogradouroActionPerformed(evt);
            }
        });

        jLabel12.setText("Cidade");

        jTxtKsmBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmBairroActionPerformed(evt);
            }
        });

        jTxtKsmCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCidadeActionPerformed(evt);
            }
        });

        jLabel13.setText("logradouro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtKsmDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jTxtKsmCodigo)
                    .addComponent(jFmtKsmCpf)
                    .addComponent(jTxtKsmNumero)
                    .addComponent(jTxtKsmLogradouro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBtnKsmIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnKsmAlterar))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabelCpf)
                            .addComponent(Código))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnKsmExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnKsmConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnKsmCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnKsmPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCboKsmNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel11)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtKsmNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jFmtKsmRg, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtKsmEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtKsmBairro))
                                .addGap(7, 7, 7)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCboKsmAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTxtKsmCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jTxtKsmCep)
                            .addComponent(jLabel8)
                            .addComponent(jTxtKsmApelido)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jTxtKsmCidade))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Código)
                        .addGap(6, 6, 6)
                        .addComponent(jTxtKsmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelCpf)
                        .addGap(6, 6, 6)
                        .addComponent(jFmtKsmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jFmtKsmDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtKsmLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtKsmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtKsmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtKsmRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jTxtKsmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtKsmBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addComponent(jTxtKsmApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtKsmCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(12, 12, 12)
                                .addComponent(jTxtKsmCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(7, 7, 7)
                                .addComponent(jTxtKsmCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCboKsmNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCboKsmAtivo)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnKsmPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnKsmExcluir)
                        .addComponent(jBtnKsmConfirmar)
                        .addComponent(jBtnKsmCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnKsmIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnKsmAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnKsmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmConfirmarActionPerformed
       // TODO add your handling code here:
      //Desabilitar();
       habilitar(false);
    }//GEN-LAST:event_jBtnKsmConfirmarActionPerformed

    private void jBtnKsmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmCancelarActionPerformed
        // TODO add your handling code here:
        //Desabilitar();
         habilitar(false);
    }//GEN-LAST:event_jBtnKsmCancelarActionPerformed

    private void jTxtKsmCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtKsmCodigoActionPerformed

    private void jBtnKsmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        
    }//GEN-LAST:event_jBtnKsmIncluirActionPerformed

    private void jBtnKsmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmAlterarActionPerformed
        // TODO add your handling code here:
          habilitar(true);
    }//GEN-LAST:event_jBtnKsmAlterarActionPerformed

    private void jBtnKsmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "confirmar a exclusao",
        "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        
    }//GEN-LAST:event_jBtnKsmExcluirActionPerformed

    private void jBtnKsmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "entre com a chave primaria");
        
    }//GEN-LAST:event_jBtnKsmPesquisarActionPerformed

    private void jCboKsmAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboKsmAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboKsmAtivoActionPerformed

    private void jTxtKsmNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmNomeActionPerformed

    private void jFmtKsmRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtKsmRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtKsmRgActionPerformed

    private void jCboKsmNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboKsmNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboKsmNivelActionPerformed

    private void jFmtKsmCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtKsmCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtKsmCpfActionPerformed

    private void jTxtKsmEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmEmailActionPerformed

    private void jTxtKsmCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmCelularActionPerformed

    private void jTxtKsmCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmCepActionPerformed

    private void jTxtKsmApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmApelidoActionPerformed

    private void jTxtKsmNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmNumeroActionPerformed

    private void jTxtKsmLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmLogradouroActionPerformed

    private void jTxtKsmBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmBairroActionPerformed

    private void jTxtKsmCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgKsmClientes dialog = new JDlgKsmClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Código;
    private javax.swing.JButton jBtnKsmAlterar;
    private javax.swing.JButton jBtnKsmCancelar;
    private javax.swing.JButton jBtnKsmConfirmar;
    private javax.swing.JButton jBtnKsmExcluir;
    private javax.swing.JButton jBtnKsmIncluir;
    private javax.swing.JButton jBtnKsmPesquisar;
    private javax.swing.JCheckBox jCboKsmAtivo;
    private javax.swing.JComboBox<String> jCboKsmNivel;
    private javax.swing.JFormattedTextField jFmtKsmCpf;
    private javax.swing.JFormattedTextField jFmtKsmDataNasc;
    private javax.swing.JFormattedTextField jFmtKsmRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtKsmApelido;
    private javax.swing.JTextField jTxtKsmBairro;
    private javax.swing.JTextField jTxtKsmCelular;
    private javax.swing.JTextField jTxtKsmCep;
    private javax.swing.JTextField jTxtKsmCidade;
    private javax.swing.JTextField jTxtKsmCodigo;
    private javax.swing.JTextField jTxtKsmEmail;
    private javax.swing.JTextField jTxtKsmLogradouro;
    private javax.swing.JTextField jTxtKsmNome;
    private javax.swing.JTextField jTxtKsmNumero;
    // End of variables declaration//GEN-END:variables
}
