/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u08766083141
 */
public class JDlgKsmFornecedores extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMpvUsuarios
     */
    public JDlgKsmFornecedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);
        
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmCnpj.setEnabled(false);
        jTxtKsmEmail.setEnabled(false);
        jTxtKsmEndereco.setEnabled(false);
        jTxtKsmNome.setEnabled(false);
        jTxtKsmTelefone.setEnabled(false);
        jTxtKsmNumero.setEnabled(false);
        jTxtKsmRazão.setEnabled(false);
        jTxtKsmCelular.setEnabled(false);
        jTxtKsmBairro.setEnabled(false);
        jTxtKsmInscricao.setEnabled(false);
        jTxtKsmCep.setEnabled(false);
        jTxtKsmCidade.setEnabled(false);
        jTxtKsmResponsavel.setEnabled(false);
        jCboKsmAtivo.setEnabled(false);
        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);
        
     
    }
    public void habilitar(boolean valor){
    jTxtKsmCodigo.setEnabled(valor);
       jTxtKsmCnpj.setEnabled(valor);
        jTxtKsmEmail.setEnabled(valor);
        jTxtKsmEndereco.setEnabled(valor);
        jTxtKsmNome.setEnabled(valor);
        jTxtKsmTelefone.setEnabled(valor);
        jTxtKsmNumero.setEnabled(valor);
        jTxtKsmRazão.setEnabled(valor);
        jTxtKsmCelular.setEnabled(valor);
        jTxtKsmBairro.setEnabled(valor);
        jTxtKsmInscricao.setEnabled(valor);
        jTxtKsmCep.setEnabled(valor);
        jTxtKsmCidade.setEnabled(valor);
        jTxtKsmResponsavel.setEnabled(valor);
        jCboKsmAtivo.setEnabled(valor);
        jBtnKsmCancelar.setEnabled(valor);
        jBtnKsmConfirmar.setEnabled(valor);

        jBtnKsmAlterar.setEnabled(! valor);
        jBtnKsmIncluir.setEnabled(! valor);
        jBtnKsmExcluir.setEnabled(! valor);
        jBtnKsmPesquisar.setEnabled(! valor);
    
    }
    public void Desabilitar (){
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmCnpj.setEnabled(false);
        jTxtKsmEmail.setEnabled(false);
        jTxtKsmEndereco.setEnabled(false);
        jTxtKsmNome.setEnabled(false);
        jTxtKsmTelefone.setEnabled(false);
        jTxtKsmNumero.setEnabled(false);
        jTxtKsmRazão.setEnabled(false);
        jTxtKsmCelular.setEnabled(false);
        jTxtKsmBairro.setEnabled(false);
        jTxtKsmInscricao.setEnabled(false);
        jTxtKsmCep.setEnabled(false);
        jTxtKsmCidade.setEnabled(false);
        jTxtKsmResponsavel.setEnabled(false);
        jCboKsmAtivo.setEnabled(false);
        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);

        jBtnKsmAlterar.setEnabled(true);
        jBtnKsmIncluir.setEnabled(true);
        jBtnKsmExcluir.setEnabled(true);
        jBtnKsmPesquisar.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtCep3 = new javax.swing.JTextField();
        Código = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtKsmCodigo = new javax.swing.JTextField();
        jTxtKsmRazão = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtKsmNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCboKsmAtivo = new javax.swing.JCheckBox();
        jBtnKsmPesquisar = new javax.swing.JButton();
        jBtnKsmCancelar = new javax.swing.JButton();
        jBtnKsmAlterar = new javax.swing.JButton();
        jBtnKsmIncluir = new javax.swing.JButton();
        jBtnKsmConfirmar = new javax.swing.JButton();
        jBtnKsmExcluir = new javax.swing.JButton();
        jTxtKsmCnpj = new javax.swing.JTextField();
        jTxtKsmInscricao = new javax.swing.JTextField();
        jTxtKsmCelular = new javax.swing.JTextField();
        jTxtKsmCep = new javax.swing.JTextField();
        jTxtKsmTelefone = new javax.swing.JTextField();
        jTxtKsmEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtKsmEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtKsmNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtKsmBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtKsmCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtKsmResponsavel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel14.setText("Cidade");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Código.setText("Código");

        jLabel1.setText("Razão Social");

        jTxtKsmCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Fantasia");

        jTxtKsmNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Inscrição Estadual");

        jLabel4.setText("Cnpj");

        jCboKsmAtivo.setText("Ativo");
        jCboKsmAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboKsmAtivoActionPerformed(evt);
            }
        });

        jBtnKsmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnKsmPesquisar.setText("Pesquisar");
        jBtnKsmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmPesquisarActionPerformed(evt);
            }
        });

        jBtnKsmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnKsmCancelar.setText("Cancelar");
        jBtnKsmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmCancelarActionPerformed(evt);
            }
        });

        jBtnKsmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnKsmAlterar.setText("Alterar");
        jBtnKsmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmAlterarActionPerformed(evt);
            }
        });

        jBtnKsmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnKsmIncluir.setText("Incluir");
        jBtnKsmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmIncluirActionPerformed(evt);
            }
        });

        jBtnKsmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnKsmConfirmar.setText("Confirmar");
        jBtnKsmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmConfirmarActionPerformed(evt);
            }
        });

        jBtnKsmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnKsmExcluir.setText("Excluir");
        jBtnKsmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmExcluirActionPerformed(evt);
            }
        });

        jTxtKsmInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmInscricaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Email");

        jLabel8.setText("Telefone");

        jLabel9.setText("Celular");

        jLabel10.setText("Cep");

        jTxtKsmEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmEnderecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Endereço");

        jTxtKsmNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmNumeroActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero");

        jTxtKsmBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmBairroActionPerformed(evt);
            }
        });

        jLabel11.setText("Bairro");

        jLabel12.setText("Cidade");

        jLabel15.setText("Responsável");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtnKsmIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnKsmAlterar)
                .addGap(12, 12, 12)
                .addComponent(jBtnKsmExcluir)
                .addGap(12, 12, 12)
                .addComponent(jBtnKsmConfirmar)
                .addGap(12, 12, 12)
                .addComponent(jBtnKsmCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnKsmPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtKsmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Código))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtKsmCnpj))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTxtKsmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTxtKsmCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel11))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jTxtKsmBairro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtKsmNumero)
                                .addComponent(jTxtKsmEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(197, 197, 197)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(183, 183, 183))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jTxtKsmRazão, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jTxtKsmNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jTxtKsmInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtKsmResponsavel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(149, 149, 149)
                                                .addComponent(jLabel13)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtKsmCep, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTxtKsmCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTxtKsmTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jCboKsmAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Código)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtKsmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtKsmCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtKsmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtKsmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKsmEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKsmTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtKsmRazão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtKsmCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(jTxtKsmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtKsmInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtKsmCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(jTxtKsmBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtKsmCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtKsmResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboKsmAtivo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnKsmConfirmar)
                    .addComponent(jBtnKsmCancelar)
                    .addComponent(jBtnKsmPesquisar)
                    .addComponent(jBtnKsmExcluir)
                    .addComponent(jBtnKsmAlterar)
                    .addComponent(jBtnKsmIncluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtKsmNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmNomeActionPerformed

    private void jBtnKsmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmConfirmarActionPerformed
       // TODO add your handling code here:
      //Desabilitar();
       habilitar(false);
    }//GEN-LAST:event_jBtnKsmConfirmarActionPerformed

    private void jBtnKsmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmCancelarActionPerformed
        // TODO add your handling code here:
        //Desabilitar();
         habilitar(false);
    }//GEN-LAST:event_jBtnKsmCancelarActionPerformed

    private void jTxtKsmCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtKsmCodigoActionPerformed

    private void jBtnKsmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        
    }//GEN-LAST:event_jBtnKsmIncluirActionPerformed

    private void jBtnKsmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmAlterarActionPerformed
        // TODO add your handling code here:
          habilitar(true);
    }//GEN-LAST:event_jBtnKsmAlterarActionPerformed

    private void jBtnKsmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "confirmar a exclusao",
        "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        
    }//GEN-LAST:event_jBtnKsmExcluirActionPerformed

    private void jBtnKsmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmPesquisarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(null, "entre com a chave primaria");
        
    }//GEN-LAST:event_jBtnKsmPesquisarActionPerformed

    private void jTxtKsmInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmInscricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmInscricaoActionPerformed

    private void jCboKsmAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboKsmAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboKsmAtivoActionPerformed

    private void jTxtKsmEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmEnderecoActionPerformed

    private void jTxtKsmNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmNumeroActionPerformed

    private void jTxtKsmBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmBairroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgKsmFornecedores dialog = new JDlgKsmFornecedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Código;
    private javax.swing.JButton jBtnKsmAlterar;
    private javax.swing.JButton jBtnKsmCancelar;
    private javax.swing.JButton jBtnKsmConfirmar;
    private javax.swing.JButton jBtnKsmExcluir;
    private javax.swing.JButton jBtnKsmIncluir;
    private javax.swing.JButton jBtnKsmPesquisar;
    private javax.swing.JCheckBox jCboKsmAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtCep3;
    private javax.swing.JTextField jTxtKsmBairro;
    private javax.swing.JTextField jTxtKsmCelular;
    private javax.swing.JTextField jTxtKsmCep;
    private javax.swing.JTextField jTxtKsmCidade;
    private javax.swing.JTextField jTxtKsmCnpj;
    private javax.swing.JTextField jTxtKsmCodigo;
    private javax.swing.JTextField jTxtKsmEmail;
    private javax.swing.JTextField jTxtKsmEndereco;
    private javax.swing.JTextField jTxtKsmInscricao;
    private javax.swing.JTextField jTxtKsmNome;
    private javax.swing.JTextField jTxtKsmNumero;
    private javax.swing.JTextField jTxtKsmRazão;
    private javax.swing.JTextField jTxtKsmResponsavel;
    private javax.swing.JTextField jTxtKsmTelefone;
    // End of variables declaration//GEN-END:variables
}
