/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u08766083141
 */
public class JDlgKsmFuncionarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMpvUsuarios
     */
    public JDlgKsmFuncionarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Funcionarios");
        setLocationRelativeTo(null);
        
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmNome.setEnabled(false);
        jTxtKsmRg.setEnabled(false);
        jTxtKsmEmail.setEnabled(false);
        jTxtKsmCargo.setEnabled(false);
        jTxtKsmTelefone.setEnabled(false);
        jTxtKsmSalario.setEnabled(false);
        jFmtKsmCpf.setEnabled(false); 
        jCboKsmAtivo.setEnabled(false);
        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);
        
     
    }
    public void habilitar(boolean valor){
        jTxtKsmCodigo.setEnabled(valor);
        jTxtKsmNome.setEnabled(valor);
        jTxtKsmRg.setEnabled(valor);
        jTxtKsmEmail.setEnabled(valor);
        jTxtKsmCargo.setEnabled(valor);
        jTxtKsmTelefone.setEnabled(valor);
        jTxtKsmSalario.setEnabled(valor);
        jFmtKsmCpf.setEnabled(valor);
        jCboKsmAtivo.setEnabled(valor);
        jBtnKsmCancelar.setEnabled(valor);
        jBtnKsmConfirmar.setEnabled(valor);

        jBtnKsmAlterar.setEnabled(! valor);
        jBtnKsmIncluir.setEnabled(! valor);
        jBtnKsmExcluir.setEnabled(! valor);
        jBtnKsmPesquisar.setEnabled(! valor);
    
    }
    public void Desabilitar (){
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmNome.setEnabled(false);
        jTxtKsmRg.setEnabled(false);
        jTxtKsmEmail.setEnabled(false);
        jTxtKsmCargo.setEnabled(false);
        jTxtKsmTelefone.setEnabled(false);
        jTxtKsmSalario.setEnabled(false);
        jFmtKsmCpf.setEnabled(false);
        jCboKsmAtivo.setEnabled(false);
        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);

        jBtnKsmAlterar.setEnabled(true);
        jBtnKsmIncluir.setEnabled(true);
        jBtnKsmExcluir.setEnabled(true);
        jBtnKsmPesquisar.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Código = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtKsmCodigo = new javax.swing.JTextField();
        jTxtKsmNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtKsmRg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCboKsmAtivo = new javax.swing.JCheckBox();
        jBtnKsmPesquisar = new javax.swing.JButton();
        jBtnKsmCancelar = new javax.swing.JButton();
        jBtnKsmAlterar = new javax.swing.JButton();
        jBtnKsmIncluir = new javax.swing.JButton();
        jBtnKsmConfirmar = new javax.swing.JButton();
        jBtnKsmExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtKsmEmail = new javax.swing.JTextField();
        jTxtKsmSalario = new javax.swing.JTextField();
        jTxtKsmTelefone = new javax.swing.JTextField();
        jTxtKsmCargo = new javax.swing.JTextField();
        jFmtKsmCpf = new javax.swing.JFormattedTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Código.setText("Código");

        jLabel1.setText("Nome");

        jTxtKsmCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Rg");

        jTxtKsmRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmRgActionPerformed(evt);
            }
        });

        jLabel3.setText("Cpf");

        jLabel4.setText("Cargo");

        jLabel6.setText("Salario");

        jCboKsmAtivo.setText("Ativo");

        jBtnKsmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnKsmPesquisar.setText("Pesquisar");
        jBtnKsmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmPesquisarActionPerformed(evt);
            }
        });

        jBtnKsmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnKsmCancelar.setText("Cancelar");
        jBtnKsmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmCancelarActionPerformed(evt);
            }
        });

        jBtnKsmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnKsmAlterar.setText("Alterar");
        jBtnKsmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmAlterarActionPerformed(evt);
            }
        });

        jBtnKsmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnKsmIncluir.setText("Incluir");
        jBtnKsmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmIncluirActionPerformed(evt);
            }
        });

        jBtnKsmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnKsmConfirmar.setText("Confirmar");
        jBtnKsmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmConfirmarActionPerformed(evt);
            }
        });

        jBtnKsmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnKsmExcluir.setText("Excluir");
        jBtnKsmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmExcluirActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefone");

        jLabel8.setText("Email");

        jTxtKsmEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmEmailActionPerformed(evt);
            }
        });

        jTxtKsmSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmSalarioActionPerformed(evt);
            }
        });

        jTxtKsmTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmTelefoneActionPerformed(evt);
            }
        });

        jTxtKsmCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Código)
                .addGap(56, 56, 56)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtKsmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTxtKsmNome, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(191, 191, 191)
                .addComponent(jLabel8))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtKsmRg, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTxtKsmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFmtKsmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTxtKsmTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(170, 170, 170)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtKsmSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTxtKsmCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jCboKsmAtivo))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnKsmIncluir)
                .addGap(9, 9, 9)
                .addComponent(jBtnKsmAlterar)
                .addGap(7, 7, 7)
                .addComponent(jBtnKsmExcluir)
                .addGap(7, 7, 7)
                .addComponent(jBtnKsmConfirmar)
                .addGap(8, 8, 8)
                .addComponent(jBtnKsmCancelar)
                .addGap(6, 6, 6)
                .addComponent(jBtnKsmPesquisar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Código)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtKsmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKsmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtKsmRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKsmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtKsmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKsmTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtKsmSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKsmCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jCboKsmAtivo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnKsmIncluir)
                    .addComponent(jBtnKsmAlterar)
                    .addComponent(jBtnKsmExcluir)
                    .addComponent(jBtnKsmConfirmar)
                    .addComponent(jBtnKsmCancelar)
                    .addComponent(jBtnKsmPesquisar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtKsmRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmRgActionPerformed

    private void jBtnKsmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmConfirmarActionPerformed
       // TODO add your handling code here:
      //Desabilitar();
       habilitar(false);
    }//GEN-LAST:event_jBtnKsmConfirmarActionPerformed

    private void jBtnKsmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmCancelarActionPerformed
        // TODO add your handling code here:
        //Desabilitar();
         habilitar(false);
    }//GEN-LAST:event_jBtnKsmCancelarActionPerformed

    private void jTxtKsmCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtKsmCodigoActionPerformed

    private void jBtnKsmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        
    }//GEN-LAST:event_jBtnKsmIncluirActionPerformed

    private void jBtnKsmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmAlterarActionPerformed
        // TODO add your handling code here:
          habilitar(true);
    }//GEN-LAST:event_jBtnKsmAlterarActionPerformed

    private void jBtnKsmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "confirmar a exclusao",
        "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        
    }//GEN-LAST:event_jBtnKsmExcluirActionPerformed

    private void jBtnKsmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmPesquisarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(null, "entre com a chave primaria");
        
    }//GEN-LAST:event_jBtnKsmPesquisarActionPerformed

    private void jTxtKsmEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmEmailActionPerformed

    private void jTxtKsmSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmSalarioActionPerformed

    private void jTxtKsmTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmTelefoneActionPerformed

    private void jTxtKsmCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgKsmFuncionarios dialog = new JDlgKsmFuncionarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Código;
    private javax.swing.JButton jBtnKsmAlterar;
    private javax.swing.JButton jBtnKsmCancelar;
    private javax.swing.JButton jBtnKsmConfirmar;
    private javax.swing.JButton jBtnKsmExcluir;
    private javax.swing.JButton jBtnKsmIncluir;
    private javax.swing.JButton jBtnKsmPesquisar;
    private javax.swing.JCheckBox jCboKsmAtivo;
    private javax.swing.JFormattedTextField jFmtKsmCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtKsmCargo;
    private javax.swing.JTextField jTxtKsmCodigo;
    private javax.swing.JTextField jTxtKsmEmail;
    private javax.swing.JTextField jTxtKsmNome;
    private javax.swing.JTextField jTxtKsmRg;
    private javax.swing.JTextField jTxtKsmSalario;
    private javax.swing.JTextField jTxtKsmTelefone;
    // End of variables declaration//GEN-END:variables
}
