/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u08766083141
 */
public class JDlgKsmVeiculos extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMpvUsuarios
     */
    public JDlgKsmVeiculos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Veiculos");
        setLocationRelativeTo(null);
        
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmStatus.setEnabled(false);
        jTxtKsmMarca.setEnabled(false);
        jTxtKsmModelo.setEnabled(false);
        jTxtKsmAno.setEnabled(false);
        jTxtKsmCor.setEnabled(false);
        jTxtKsmPlaca.setEnabled(false);
        jTxtKsmChassi.setEnabled(false);
        jTxtKsmValorCompra.setEnabled(false);
        jTxtKsmValorVenda.setEnabled(false);
        
        
        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);
        
     
    }
    public void habilitar(boolean valor){
        jTxtKsmCodigo.setEnabled(valor);
        jTxtKsmStatus.setEnabled(valor);
        jTxtKsmMarca.setEnabled(valor);
        jTxtKsmModelo.setEnabled(valor);
        jTxtKsmAno.setEnabled(valor);
        jTxtKsmCor.setEnabled(valor);
        jTxtKsmPlaca.setEnabled(valor);
        jTxtKsmChassi.setEnabled(valor);
        jTxtKsmValorCompra.setEnabled(valor);
        jTxtKsmValorVenda.setEnabled(valor);
      
        jBtnKsmCancelar.setEnabled(valor);
        jBtnKsmConfirmar.setEnabled(valor);
        jBtnKsmAlterar.setEnabled(! valor);
        jBtnKsmIncluir.setEnabled(! valor);
        jBtnKsmExcluir.setEnabled(! valor);
        jBtnKsmPesquisar.setEnabled(! valor);
    
    }
    public void Desabilitar (){
        jTxtKsmCodigo.setEnabled(false);
        jTxtKsmStatus.setEnabled(false);
        jTxtKsmMarca.setEnabled(false);
        jTxtKsmModelo.setEnabled(false);
        jTxtKsmAno.setEnabled(false);
        jTxtKsmCor.setEnabled(false);
        jTxtKsmPlaca.setEnabled(false);
        jTxtKsmChassi.setEnabled(false);
        jTxtKsmValorCompra.setEnabled(false);
        jTxtKsmValorVenda.setEnabled(false);

        jBtnKsmCancelar.setEnabled(false);
        jBtnKsmConfirmar.setEnabled(false);

        jBtnKsmAlterar.setEnabled(true);
        jBtnKsmIncluir.setEnabled(true);
        jBtnKsmExcluir.setEnabled(true);
        jBtnKsmPesquisar.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Código = new javax.swing.JLabel();
        jTxtKsmCodigo = new javax.swing.JTextField();
        jTxtKsmChassi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtKsmModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnKsmPesquisar = new javax.swing.JButton();
        jBtnKsmCancelar = new javax.swing.JButton();
        jBtnKsmAlterar = new javax.swing.JButton();
        jBtnKsmIncluir = new javax.swing.JButton();
        jBtnKsmConfirmar = new javax.swing.JButton();
        jBtnKsmExcluir = new javax.swing.JButton();
        jTxtKsmPlaca = new javax.swing.JTextField();
        jTxtKsmAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtKsmStatus = new javax.swing.JTextField();
        Código1 = new javax.swing.JLabel();
        jTxtKsmMarca = new javax.swing.JTextField();
        jTxtKsmCor = new javax.swing.JTextField();
        jTxtKsmValorCompra = new javax.swing.JTextField();
        jTxtKsmValorVenda = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Código.setText("Código");

        jTxtKsmCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca");

        jTxtKsmModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmModeloActionPerformed(evt);
            }
        });

        jLabel3.setText("Cor");

        jLabel4.setText("Modelo");

        jLabel5.setText("Placa");

        jLabel6.setText("Ano");

        jBtnKsmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnKsmPesquisar.setText("Pesquisar");
        jBtnKsmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmPesquisarActionPerformed(evt);
            }
        });

        jBtnKsmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnKsmCancelar.setText("Cancelar");
        jBtnKsmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmCancelarActionPerformed(evt);
            }
        });

        jBtnKsmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnKsmAlterar.setText("Alterar");
        jBtnKsmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmAlterarActionPerformed(evt);
            }
        });

        jBtnKsmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnKsmIncluir.setText("Incluir");
        jBtnKsmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmIncluirActionPerformed(evt);
            }
        });

        jBtnKsmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnKsmConfirmar.setText("Confirmar");
        jBtnKsmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmConfirmarActionPerformed(evt);
            }
        });

        jBtnKsmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnKsmExcluir.setText("Excluir");
        jBtnKsmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmExcluirActionPerformed(evt);
            }
        });

        jLabel7.setText("Chassi");

        jLabel8.setText("Valor Compra");

        jLabel9.setText("Valor Venda");

        jTxtKsmStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmStatusActionPerformed(evt);
            }
        });

        Código1.setText("Status");

        jTxtKsmMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Código)
                    .addComponent(jTxtKsmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnKsmIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnKsmAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnKsmExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnKsmConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtKsmModelo)
                                .addComponent(jLabel4)
                                .addComponent(jTxtKsmAno, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(jTxtKsmMarca))
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jTxtKsmPlaca)
                            .addComponent(jTxtKsmChassi)
                            .addComponent(jTxtKsmCor, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jTxtKsmValorVenda)
                            .addComponent(Código1)
                            .addComponent(jTxtKsmStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jTxtKsmValorCompra))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnKsmCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnKsmPesquisar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Código)
                .addGap(6, 6, 6)
                .addComponent(jTxtKsmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(jTxtKsmMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtKsmModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtKsmValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtKsmValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Código1)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtKsmAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtKsmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jTxtKsmCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtKsmPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtKsmChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnKsmIncluir)
                    .addComponent(jBtnKsmAlterar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnKsmExcluir)
                        .addComponent(jBtnKsmConfirmar)
                        .addComponent(jBtnKsmCancelar)
                        .addComponent(jBtnKsmPesquisar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtKsmModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmModeloActionPerformed

    private void jBtnKsmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmConfirmarActionPerformed
       // TODO add your handling code here:
      //Desabilitar();
       habilitar(false);
    }//GEN-LAST:event_jBtnKsmConfirmarActionPerformed

    private void jBtnKsmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmCancelarActionPerformed
        // TODO add your handling code here:
        //Desabilitar();
         habilitar(false);
    }//GEN-LAST:event_jBtnKsmCancelarActionPerformed

    private void jTxtKsmCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtKsmCodigoActionPerformed

    private void jBtnKsmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        
    }//GEN-LAST:event_jBtnKsmIncluirActionPerformed

    private void jBtnKsmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmAlterarActionPerformed
        // TODO add your handling code here:
          habilitar(true);
    }//GEN-LAST:event_jBtnKsmAlterarActionPerformed

    private void jBtnKsmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "confirmar a exclusao",
        "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        
    }//GEN-LAST:event_jBtnKsmExcluirActionPerformed

    private void jBtnKsmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmPesquisarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(null, "entre com a chave primaria");
        
    }//GEN-LAST:event_jBtnKsmPesquisarActionPerformed

    private void jTxtKsmStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmStatusActionPerformed

    private void jTxtKsmMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgKsmVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgKsmVeiculos dialog = new JDlgKsmVeiculos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Código;
    private javax.swing.JLabel Código1;
    private javax.swing.JButton jBtnKsmAlterar;
    private javax.swing.JButton jBtnKsmCancelar;
    private javax.swing.JButton jBtnKsmConfirmar;
    private javax.swing.JButton jBtnKsmExcluir;
    private javax.swing.JButton jBtnKsmIncluir;
    private javax.swing.JButton jBtnKsmPesquisar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtKsmAno;
    private javax.swing.JTextField jTxtKsmChassi;
    private javax.swing.JTextField jTxtKsmCodigo;
    private javax.swing.JTextField jTxtKsmCor;
    private javax.swing.JTextField jTxtKsmMarca;
    private javax.swing.JTextField jTxtKsmModelo;
    private javax.swing.JTextField jTxtKsmPlaca;
    private javax.swing.JTextField jTxtKsmStatus;
    private javax.swing.JTextField jTxtKsmValorCompra;
    private javax.swing.JTextField jTxtKsmValorVenda;
    // End of variables declaration//GEN-END:variables
}
