/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author u08766083141
 * 
 */
public class JFrmTeste extends javax.swing.JFrame {

    /**
     * Creates new form JFrmTeste
     * construtor
     */
    public JFrmTeste() {
        initComponents();
        jBtnHabilitar.setEnabled(false);
        jBtnVisivel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNome = new javax.swing.JLabel();
        jTxtKsmNome = new javax.swing.JTextField();
        jLblTipo = new javax.swing.JLabel();
        jCboKsmTipo = new javax.swing.JComboBox<>();
        jBtnDesabilitar = new javax.swing.JButton();
        jBtnHabilitar = new javax.swing.JButton();
        jBtnInvisivel = new javax.swing.JButton();
        jBtnVisivel = new javax.swing.JButton();
        jBtnKsmTeste = new javax.swing.JButton();
        jBtnKsmLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblNome.setText("Nome");

        jTxtKsmNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtKsmNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtKsmNomeFocusLost(evt);
            }
        });
        jTxtKsmNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKsmNomeActionPerformed(evt);
            }
        });

        jLblTipo.setText("Tipo");

        jBtnDesabilitar.setText("Desabilitar");
        jBtnDesabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDesabilitarActionPerformed(evt);
            }
        });

        jBtnHabilitar.setText("Habilitar");
        jBtnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHabilitarActionPerformed(evt);
            }
        });

        jBtnInvisivel.setText("invisivel");
        jBtnInvisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInvisivelActionPerformed(evt);
            }
        });

        jBtnVisivel.setText("visivel");
        jBtnVisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVisivelActionPerformed(evt);
            }
        });

        jBtnKsmTeste.setText("teste");
        jBtnKsmTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmTesteActionPerformed(evt);
            }
        });

        jBtnKsmLimpar.setText("Limpar");
        jBtnKsmLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKsmLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblNome)
                            .addComponent(jLblTipo)
                            .addComponent(jCboKsmTipo, 0, 212, Short.MAX_VALUE)
                            .addComponent(jTxtKsmNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnKsmLimpar)
                            .addComponent(jBtnKsmTeste)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnDesabilitar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnHabilitar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnInvisivel)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnVisivel)))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtKsmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnKsmLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboKsmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnKsmTeste))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDesabilitar)
                    .addComponent(jBtnHabilitar)
                    .addComponent(jBtnInvisivel)
                    .addComponent(jBtnVisivel))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtKsmNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKsmNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKsmNomeActionPerformed

    private void jBtnDesabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDesabilitarActionPerformed
        // TODO add your handling code here:
        jTxtKsmNome.setEnabled(false);
        jCboKsmTipo.setEnabled(false);
        jBtnDesabilitar.setEnabled(false);
        jBtnHabilitar.setEnabled(true);
        
        
    }//GEN-LAST:event_jBtnDesabilitarActionPerformed

    private void jBtnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHabilitarActionPerformed
        // TODO add your handling code here:
        jTxtKsmNome.setEnabled(true);
        jCboKsmTipo.setEnabled(true);
        jBtnDesabilitar.setEnabled(true);
        jBtnHabilitar.setEnabled(false);
    }//GEN-LAST:event_jBtnHabilitarActionPerformed

    private void jBtnInvisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInvisivelActionPerformed
        // TODO add your handling code here:
        jTxtKsmNome.setVisible(false);
        jCboKsmTipo.setVisible(false);
        jBtnDesabilitar.setVisible(false);
        jBtnHabilitar.setVisible(false);
      
        jBtnVisivel.setEnabled(true);
        jBtnInvisivel.setEnabled(false);
    }//GEN-LAST:event_jBtnInvisivelActionPerformed

    private void jBtnVisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVisivelActionPerformed
        // TODO add your handling code here:
         jTxtKsmNome.setVisible(true);
        jCboKsmTipo.setVisible(true);
        jBtnDesabilitar.setVisible(true);
        jBtnHabilitar.setVisible(true);
    jBtnVisivel.setEnabled(false);
        jBtnInvisivel.setEnabled(true);

       
    }//GEN-LAST:event_jBtnVisivelActionPerformed

    private void jBtnKsmTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmTesteActionPerformed
        // TODO add your handling code here:
 //        if( jCboTipo.isEnabled() == true){
 //         jTxtNome.setEnabled(false);
  //        jCboTipo.setEnabled(false);
 //        }else{
 //            jCboTipo.
   //      }
   boolean estado= jCboKsmTipo.isEnabled();
   jTxtKsmNome.setEnabled(!estado);
   jCboKsmTipo.setEnabled(!estado);
      
     
    }//GEN-LAST:event_jBtnKsmTesteActionPerformed

    private void jBtnKsmLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKsmLimparActionPerformed
        // TODO add your handling code here:
        jTxtKsmNome.setText("");
    }//GEN-LAST:event_jBtnKsmLimparActionPerformed

    private void jTxtKsmNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtKsmNomeFocusGained
        // TODO add your handling code here:
        jTxtKsmNome.setBackground(Color.cyan);
    }//GEN-LAST:event_jTxtKsmNomeFocusGained

    private void jTxtKsmNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtKsmNomeFocusLost
        // TODO add your handling code here:
         jTxtKsmNome.setBackground(Color.white);
    }//GEN-LAST:event_jTxtKsmNomeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDesabilitar;
    private javax.swing.JButton jBtnHabilitar;
    private javax.swing.JButton jBtnInvisivel;
    private javax.swing.JButton jBtnKsmLimpar;
    private javax.swing.JButton jBtnKsmTeste;
    private javax.swing.JButton jBtnVisivel;
    private javax.swing.JComboBox<String> jCboKsmTipo;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblTipo;
    private javax.swing.JTextField jTxtKsmNome;
    // End of variables declaration//GEN-END:variables
}
