/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u08766083141
 */
public class JFrmKsmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmKsmPrincipal() {
        initComponents();
        setTitle("Sistema do IFMS");
        setExtendedState(MAXIMIZED_BOTH);
        JDlgKsmTelaLogin jDlgKsmTelaLogin = new JDlgKsmTelaLogin(this,true);
        jDlgKsmTelaLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1Ksm = new javax.swing.JMenuBar();
        jMnuKsmCadastro = new javax.swing.JMenu();
        jMnuKsmUsuarios = new javax.swing.JMenuItem();
        jMnuKsmClientes = new javax.swing.JMenuItem();
        jMnuKsmFuncionarios = new javax.swing.JMenuItem();
        jMnuKsmVeiculos = new javax.swing.JMenuItem();
        jMnuKsmFornecedor = new javax.swing.JMenuItem();
        jSeparator1Ksm = new javax.swing.JPopupMenu.Separator();
        jMnuKsmSair = new javax.swing.JMenuItem();
        jMnuKsmMovimentos = new javax.swing.JMenu();
        jMnuKsmVendas = new javax.swing.JRadioButtonMenuItem();
        jMnuKsmCompras = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuKsmCadastro.setMnemonic('d');
        jMnuKsmCadastro.setText("Cadastros");

        jMnuKsmUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuKsmUsuarios.setMnemonic('U');
        jMnuKsmUsuarios.setText("Usuarios");
        jMnuKsmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKsmUsuariosActionPerformed(evt);
            }
        });
        jMnuKsmCadastro.add(jMnuKsmUsuarios);

        jMnuKsmClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-homem-de-negócios-30.png"))); // NOI18N
        jMnuKsmClientes.setMnemonic('C');
        jMnuKsmClientes.setText("Clientes");
        jMnuKsmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKsmClientesActionPerformed(evt);
            }
        });
        jMnuKsmCadastro.add(jMnuKsmClientes);

        jMnuKsmFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-grupo-de-negócios-30.png"))); // NOI18N
        jMnuKsmFuncionarios.setMnemonic('F');
        jMnuKsmFuncionarios.setText("Funcionarios");
        jMnuKsmFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKsmFuncionariosActionPerformed(evt);
            }
        });
        jMnuKsmCadastro.add(jMnuKsmFuncionarios);

        jMnuKsmVeiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-carro-30.png"))); // NOI18N
        jMnuKsmVeiculos.setMnemonic('E');
        jMnuKsmVeiculos.setText("Veiculos");
        jMnuKsmVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKsmVeiculosActionPerformed(evt);
            }
        });
        jMnuKsmCadastro.add(jMnuKsmVeiculos);

        jMnuKsmFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-fornecedor-24.png"))); // NOI18N
        jMnuKsmFornecedor.setMnemonic('O');
        jMnuKsmFornecedor.setText("Fornecedor");
        jMnuKsmFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKsmFornecedorActionPerformed(evt);
            }
        });
        jMnuKsmCadastro.add(jMnuKsmFornecedor);
        jMnuKsmCadastro.add(jSeparator1Ksm);

        jMnuKsmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jMnuKsmSair.setMnemonic('S');
        jMnuKsmSair.setText("Sair");
        jMnuKsmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKsmSairActionPerformed(evt);
            }
        });
        jMnuKsmCadastro.add(jMnuKsmSair);

        jMenuBar1Ksm.add(jMnuKsmCadastro);

        jMnuKsmMovimentos.setMnemonic('M');
        jMnuKsmMovimentos.setText("Movimentos");

        jMnuKsmVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmVendas.setMnemonic('v');
        jMnuKsmVendas.setSelected(true);
        jMnuKsmVendas.setText("Vendas");
        jMnuKsmVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-vendas-totais-24.png"))); // NOI18N
        jMnuKsmVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKsmVendasActionPerformed(evt);
            }
        });
        jMnuKsmMovimentos.add(jMnuKsmVendas);

        jMnuKsmCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuKsmCompras.setMnemonic('p');
        jMnuKsmCompras.setSelected(true);
        jMnuKsmCompras.setText("Compras");
        jMnuKsmCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-carrinho-de-compras-24.png"))); // NOI18N
        jMnuKsmMovimentos.add(jMnuKsmCompras);

        jMenuBar1Ksm.add(jMnuKsmMovimentos);

        setJMenuBar(jMenuBar1Ksm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuKsmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKsmClientesActionPerformed
        // TODO add your handling code here:
        JDlgKsmClientes jDlgKsmClientes = new JDlgKsmClientes(null, true);
        jDlgKsmClientes.setVisible(true);
    }//GEN-LAST:event_jMnuKsmClientesActionPerformed

    private void jMnuKsmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKsmUsuariosActionPerformed
        // TODO add your handling code here:
        //classe letra maiuscula  objeto minuscula chama contructor maiusculo null pai true modal
        JDlgKsmUsuarios jDlgKsmUsuarios= new JDlgKsmUsuarios(null, true);
        jDlgKsmUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuKsmUsuariosActionPerformed

    private void jMnuKsmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKsmSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuKsmSairActionPerformed

    private void jMnuKsmVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKsmVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuKsmVendasActionPerformed

    private void jMnuKsmFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKsmFornecedorActionPerformed
        // TODO add your handling code here:
        JDlgKsmFornecedores jDlgKsmFornecedores = new JDlgKsmFornecedores(null, true);
        jDlgKsmFornecedores.setVisible(true);
    }//GEN-LAST:event_jMnuKsmFornecedorActionPerformed

    private void jMnuKsmFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKsmFuncionariosActionPerformed
        // TODO add your handling code here:
        JDlgKsmFuncionarios jDlgKsmFuncionarios = new  JDlgKsmFuncionarios(null, true);
        jDlgKsmFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMnuKsmFuncionariosActionPerformed

    private void jMnuKsmVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKsmVeiculosActionPerformed
        // TODO add your handling code here:
        JDlgKsmVeiculos jDlgKsmVeiculos = new JDlgKsmVeiculos(null, true);
        jDlgKsmVeiculos.setVisible(true);
    }//GEN-LAST:event_jMnuKsmVeiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmKsmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmKsmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmKsmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmKsmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmKsmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1Ksm;
    private javax.swing.JMenu jMnuKsmCadastro;
    private javax.swing.JMenuItem jMnuKsmClientes;
    private javax.swing.JRadioButtonMenuItem jMnuKsmCompras;
    private javax.swing.JMenuItem jMnuKsmFornecedor;
    private javax.swing.JMenuItem jMnuKsmFuncionarios;
    private javax.swing.JMenu jMnuKsmMovimentos;
    private javax.swing.JMenuItem jMnuKsmSair;
    private javax.swing.JMenuItem jMnuKsmUsuarios;
    private javax.swing.JMenuItem jMnuKsmVeiculos;
    private javax.swing.JRadioButtonMenuItem jMnuKsmVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1Ksm;
    // End of variables declaration//GEN-END:variables
}
